// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;
import {console} from "forge-std/Test.sol";

contract Homework {
    uint256 public root = 14365581408805830113492150575347581743198651727460587671054435435458023396354;
    IMIMC public mimc; // generated by circomlibjs/src/mimc7_gencontract.js

    constructor(address _mimc) {
        mimc = IMIMC(_mimc);
    }

    function verify(uint256 l1, uint256 l2) public view {
        uint128 _l1 = uint128(l1);
        uint128 _l2 = uint128(l2);
        uint256 concatenated = concat(_l1, _l2);
        console.log("concatenated: ", concatenated);

        // get mimc hash: use l1+l2 as input, for 91 rounds
        // concatenated = 419908440780438063913804265570801972938041
        // mimc hash = 14365581408805830113492150575347581743198651727460587671054435435458023396354
        uint256 out_x = mimc.MiMCpe7(concatenated, 1314521);
        console.log("out_x: ", out_x);
        require(out_x == root, "verification failed");
    }

    // Source: https://ethereum.stackexchange.com/a/72347
    function concat(uint128 a, uint128 b) public pure returns (uint256) {
        return uint256(bytes32(uint256(a) << 128 | b));
    }
}

interface IMIMC {
  function MiMCpe7(uint256 in_x, uint256 in_k) external pure returns (uint256);
}
