// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Homework {
    uint256 public constant ROOT = 14365581408805830113492150575347581743198651727460587671054435435458023396354;
    uint256 public constant MIMC_KEY = 1_314_521;

    IMIMC public immutable mimc; // generated by circomlibjs/src/mimc7_gencontract.js

    constructor(address _mimc) {
        require(_mimc.code.length > 0, "invalid mimc");
        mimc = IMIMC(_mimc);
    }

    function verify(uint256 l1, uint256 l2) public view returns (bool) {
        require(l1 <= type(uint128).max && l2 <= type(uint128).max, "leaf too large");

        uint128 _l1 = uint128(l1);
        uint128 _l2 = uint128(l2);
        uint256 concatenated = concat(_l1, _l2);

        // get mimc hash: use l1+l2 as input, for 91 rounds
        // concatenated = 419908440780438063913804265570801972938041
        // mimc hash = 14365581408805830113492150575347581743198651727460587671054435435458023396354
        uint256 out_x = mimc.MiMCpe7(concatenated, MIMC_KEY);
        require(out_x == ROOT, "verification failed");

        return true;
    }

    function concat(uint128 a, uint128 b) public pure returns (uint256) {
        return (uint256(a) << 128) | uint256(b);
    }
}

interface IMIMC {
    function MiMCpe7(uint256 in_x, uint256 in_k) external pure returns (uint256);
}
